version: '3.8'
name: oneclickteach
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: pnpm run start:dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
      - database
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    env_file:
      - .env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped

  database:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d # Mount seed data
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data:
